services:
  db:
    image: postgres:17.0
    restart: always
    env_file:
      - ~/config/.env
    volumes:
      - pgdata_sovarouter:/var/lib/postgresql/data
    ports:
      - 5441:5432 # Don't forget to add rule to firewall
    depends_on:
      - dozzle
    labels:
      - group=sovarouter
      - dev.dozzle.name=database

  bot:
    image: sovarouter_bot:latest
    build:
      context: .
    env_file:
      - ~/config/.env
    volumes:
      - ~/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db
    labels:
      - group=sovarouter
      - dev.dozzle.name=bot

volumes:
  pgdata_sovarouter:
